[package]
name = "autogen-core"
version = "0.1.0"
edition = "2021"

[dependencies]
chatgpt_rs = "1.2.3"
serde = { version = "1.0.193", features = ["derive"] }
thiserror = "1.0.51"
tokio = { version = "1.35.1", features = ["full"] }
toml = "0.8.8"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
